### ISSUE TITLE
Explore framework for microSWIFT/raspberry pi emulation

### ISSUE THREAD

**Issue by jacobrdavis** [SASlabgroup/microSWIFT#25]
We need a means of running operational scripts (`microSWIFT.py`, `checkout.py`, + other code that interface directly with hardware) without having a physical microSWIFT online. This will require some combination of emulators -- [RPi.GPIO](https://pypi.org/project/RPi.GPIO/), [serial emulation](https://pyserial.readthedocs.io/en/latest/shortintro.html), a Docker container -- and (possibly) mock classes that will return data without the presence of a physical component (e.g. GPS). In the best case, a developer will be able to activate a development virtual environment and run/diagnose scripts such as `microSWIFT.py` while offline. 

The goal of this issue is to download, test, and combine several of these emulators into a framework for microSWIFT emulation.

**Comment by cranders-bio** [comment]
Hey @edwinrainville @jacobrdavis 

I've done a little bit of work on the emulator today and I have figured out how to get it up and running with docker and even how to pull down the microSWIFT repo onto the image. When you use the real raspberry pi though, what happens after you pull the repo down? Do you put the project file anywhere special? Or can you just restart it and have it start working?

**Comment by edwinrainville** [comment]
@cranders-bio Once you pull it onto the pi you will need to make a data directory and a logs directory but then you should be able to just run it there. Since we did some restructuring, some functions may need to be moved around so they can be found.
